[package]
name = "qust"
version = "0.1.2"
edition = "2021"
authors = ["baiguo<aruster@qq.com>"]
description = "A crate for finance quantative reserach"
license = "MIT OR Apache-2.0"

[lib]
name = "qust"
path = "src/lib.rs"

[dependencies]
