[dependencies]
qust-derive = { path = "../../qust-derive", version = "*" }
qust-ds = { path= "../../qust-ds", version = "*"}
qust = { path = "../../qust", version = "*" }
qust-io = { path = "../../qust-io", version = "*" }
qust-stra = { path = "../../qust-stra", version = "*" }
num-traits = { version = ">= 0.0.0" }
itertools = "*"
typetag = { version = ">= 0.2.5"}
serde = { version =  ">= 1.0.136", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
regex = ">=1.10.4"
ta = { version = "0.5.0" }


[evcxr]
tmpdir = "./tmpdir"
prelude = """
use qust::prelude::*;
use qust::std_prelude::*;
use qust_ds::prelude::*;
use qust_derive::*;
use qust_io::prelude::*;
use qust_stra::prelude::*;
use serde::{Serialize, Deserialize};
use chrono::{Timelike, Duration};
use ta::{ Next, indicators::SimpleMovingAverage as SMA };
"""
